// Copyright (c) 2026 Greg Bussell
// SPDX-License-Identifier: MIT

#include "SimpleQuestEditor.h"
#include "AssetTypes/QuestlineGraphAssetTypeActions.h"
#include "AssetToolsModule.h"
#include "Modules/ModuleManager.h"
#include "EdGraphUtilities.h"
#include "GameplayTagRedirectors.h"
#include "GameplayTagsManager.h"
#include "GameplayTagsSettings.h"
#include "MessageLogModule.h"
#include "Subsystems/AssetEditorSubsystem.h"
#include "Editor.h"
#include "Engine/Blueprint.h"
#include "EdGraph/EdGraph.h"
#include "Utilities/QuestlineGraphCompiler.h"
#include "SGraphNodeKnot.h"
#include "SimpleQuestLog.h"
#include "Graph/QuestlineGraphSchema.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Nodes/QuestlineNode_Knot.h"
#include "Settings/SimpleQuestSettings.h"
#include "Toolkit/QuestlineGraphEditorCommands.h"
#include "Utilities/QuestTagComposer.h"
#include "Engine/Blueprint.h"
#include "Quests/QuestlineGraph.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Framework/Notifications/NotificationManager.h"
#include "Misc/FileHelper.h"
#include "HAL/FileManager.h"
#include "Interfaces/IPluginManager.h"
#include "Nodes/QuestlineNode_Step.h"
#include "Nodes/Groups/QuestlineNode_PortalExitBase.h"
#include "Nodes/Groups/QuestlineNode_PortalEntryBase.h"
#include "Nodes/Prerequisites/QuestlineNode_PrerequisiteAnd.h"
#include "Nodes/Prerequisites/QuestlineNode_PrerequisiteBase.h"
#include "Nodes/Prerequisites/QuestlineNode_PrerequisiteNot.h"
#include "Nodes/Prerequisites/QuestlineNode_PrerequisiteOr.h"
#include "Nodes/Utility/QuestlineNode_UtilityBase.h"
#include "Nodes/Slate/SGraphNode_GroupNode.h"
#include "Nodes/Slate/SGraphNode_PrerequisiteCombinator.h"
#include "Nodes/Slate/SGraphNode_QuestlineStep.h"
#include "Nodes/Slate/SGraphNode_UtilityNode.h"
#include "Resolver/QuestDataFormatRegistry.h"
#include "Resolver/TsvQuestDataFormat.h"
#include "Resolver/JsonQuestDataFormat.h"
#include "Styling/SlateStyle.h"
#include "Styling/SlateStyleRegistry.h"
#include "Brushes/SlateImageBrush.h"
#include "Brushes/SlateRoundedBoxBrush.h"
#include "Styling/StyleColors.h"
#include "Debug/QuestPIEDebugChannel.h"
#include "DetailCustomizations/QuestlineNodeEntryDetailsCustomization.h"
#include "Nodes/QuestlineNode_Entry.h"
#include "Nodes/QuestlineNode_Exit.h"
#include "Nodes/QuestlineNode_LinkedQuestline.h"
#include "Nodes/QuestlineNode_Quest.h"
#include "Nodes/Slate/SGraphNode_Exit.h"
#include "Nodes/Slate/SGraphNode_LinkedQuestline.h"
#include "Nodes/Slate/SGraphNode_QuestlineQuest.h"
#include "UObject/SavePackage.h"
#include "Utilities/SimpleQuestEditorUtils.h"
#include "Widgets/Notifications/SNotificationList.h"
#include "WorkspaceMenuStructure.h"
#include "WorkspaceMenuStructureModule.h"
#include "DetailCustomizations/QuestImportMappingDetailsCustomization.h"
#include "DetailCustomizations/QuestlineGraphRewardsDetailsCustomization.h"
#include "FactsPanel/FactsPanelRegistry.h"
#include "K2Nodes/K2Node_ObserveQuestLifecycle.h"
#include "K2Nodes/K2Node_CompleteObjectiveWithOutcome.h"
#include "Resolver/QuestImportMapping.h"
#include "Widgets/SQuestStateView.h"
#include "Widgets/SStaleQuestTagsPanel.h"


const FName FSimpleQuestEditor::StaleQuestTagsTabId(TEXT("SimpleQuest.StaleQuestTags"));

namespace
{
	/**
	 * ViewID for the Quest State view in the generic FactsPanelRegistry. Stable string used as the dropdown
	 * selection key inside SFactsPanel. File-scope since no other translation unit needs to reference it.
	 */
	const FName QuestStateViewId(TEXT("SimpleQuest.Questline.State"));

	// The display ini is sectioned: [EffectiveID] headers over "Tag=..." lines. Parse drops comments/blanks; the
    // writer regenerates the header. Keyed by EffectiveID so each graph owns exactly one section.
    TMap<FString, TArray<FString>> ParseDisplaySections(const FString& Content)
    {
        TMap<FString, TArray<FString>> Sections;
        TArray<FString> Lines;
        Content.ParseIntoArrayLines(Lines);
        FString Current;
        for (FString Line : Lines)
        {
            Line.TrimStartAndEndInline();
            if (Line.IsEmpty() || Line.StartsWith(TEXT(";"))) continue;
            if (Line.StartsWith(TEXT("[")) && Line.EndsWith(TEXT("]"))) { Current = Line.Mid(1, Line.Len() - 2); Sections.FindOrAdd(Current); }
            else if (!Current.IsEmpty()) { Sections.FindOrAdd(Current).Add(Line); }
        }
        return Sections;
    }

    FString SerializeDisplaySections(const TMap<FString, TArray<FString>>& Sections)
    {
        TArray<FString> Keys; Sections.GetKeys(Keys); Keys.Sort();   // deterministic section order
        FString Out =
            TEXT("; ==========================================================================\n")
            TEXT("; AUTO-GENERATED by SimpleQuest compiler. DO NOT EDIT.\n")
            TEXT("; Per-questline display: Tag=Name|Description|DisplayDataPath (loc-preserving FText export).\n")
            TEXT("; ==========================================================================\n");
        for (const FString& Key : Keys)
        {
            const TArray<FString>& Records = Sections[Key];
            if (Records.Num() == 0) continue;   // never emit an empty section
            Out += FString::Printf(TEXT("[%s]\n"), *Key);
            for (const FString& Record : Records) { Out += Record; Out += TEXT("\n"); }
        }
        return Out;
    }

    void WriteSectionsToDisk(const FString& IniPath, const TMap<FString, TArray<FString>>& Sections)
    {
        const FString Dir = FPaths::GetPath(IniPath);
        if (!IFileManager::Get().DirectoryExists(*Dir)) IFileManager::Get().MakeDirectory(*Dir, true);
        FFileHelper::SaveStringToFile(SerializeDisplaySections(Sections), *IniPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
    }
}

IMPLEMENT_MODULE(FSimpleQuestEditor, SimpleQuestEditor);

FString FSimpleQuestEditor::GetCompiledTagsIniPath()
{
	// Generated, per-project data, so it lives with the consuming project instead of the plugin folder. An engine-installed
	// plugin sits under the shared, potentially read-only engine directory, where writing may fail and the file could neither
	// travel with nor stay isolated to a single project. A dedicated subfolder (not Config/Tags/) keeps this auto-generated,
	// compile-overwritten file out of the Gameplay Tag editor's save-picker. StartupModule registers this directory as a
	// gameplay-tag search path, which the manager re-applies on every tag-tree rebuild.
	return FPaths::ConvertRelativePathToFull(FPaths::ProjectConfigDir() / TEXT("SimpleQuest/SimpleQuestCompiledTags.ini"));
}

class FQuestlineGraphNodeFactory : public FGraphPanelNodeFactory
{
	virtual TSharedPtr<SGraphNode> CreateNode(UEdGraphNode* Node) const override
	{
		if (UQuestlineNode_Knot* KnotNode = Cast<UQuestlineNode_Knot>(Node))
		{
			return SNew(SGraphNodeKnot, KnotNode);
		}
		if (Cast<UQuestlineNode_PrerequisiteAnd>(Node)
			|| Cast<UQuestlineNode_PrerequisiteOr>(Node)
			|| Cast<UQuestlineNode_PrerequisiteNot>(Node))
		{
			return SNew(SGraphNode_PrerequisiteCombinator, CastChecked<UQuestlineNode_PrerequisiteBase>(Node));
		}
		if (Cast<UQuestlineNode_PortalEntryBase>(Node) || Cast<UQuestlineNode_PortalExitBase>(Node))
		{
			return SNew(SGraphNode_GroupNode, Node);
		}
		if (Cast<UQuestlineNode_UtilityBase>(Node))
		{
			return SNew(SGraphNode_UtilityNode, Node);
		}
		if (UQuestlineNode_Step* StepNode = Cast<UQuestlineNode_Step>(Node))
		{
			return SNew(SGraphNode_QuestlineStep, StepNode);
		}
		if (UQuestlineNode_LinkedQuestline* LinkedNode = Cast<UQuestlineNode_LinkedQuestline>(Node))
		{
			return SNew(SGraphNode_LinkedQuestline, LinkedNode);
		}
		if (UQuestlineNode_Quest* QuestNode = Cast<UQuestlineNode_Quest>(Node))
		{
			return SNew(SGraphNode_QuestlineQuest, QuestNode);
		}
		if (UQuestlineNode_Exit* ExitNode = Cast<UQuestlineNode_Exit>(Node))
		{
			return SNew(SGraphNode_Exit, ExitNode);
		}
		return nullptr;
	}
};

void FSimpleQuestEditor::StartupModule()
{
	IAssetTools& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>("AssetTools").Get();
	QuestlineGraphAssetTypeActions = MakeShared<FQuestlineGraphAssetTypeActions>();
	AssetTools.RegisterAssetTypeActions(QuestlineGraphAssetTypeActions.ToSharedRef());

	QuestlineGraphNodeFactory = MakeShared<FQuestlineGraphNodeFactory>();
	FEdGraphUtilities::RegisterVisualNodeFactory(QuestlineGraphNodeFactory);

	QuestlineConnectionFactory = UQuestlineGraphSchema::MakeQuestlineConnectionFactory();
	FEdGraphUtilities::RegisterVisualPinConnectionFactory(QuestlineConnectionFactory);
	
	FQuestlineGraphEditorCommands::Register();

	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>("PropertyEditor");
	PropertyModule.RegisterCustomClassLayout(UQuestlineNode_Entry::StaticClass()->GetFName(), FOnGetDetailCustomizationInstance::CreateStatic(&FQuestlineNodeEntryDetailsCustomization::MakeInstance));
	PropertyModule.RegisterCustomClassLayout(UQuestlineGraph::StaticClass()->GetFName(), FOnGetDetailCustomizationInstance::CreateStatic(&FQuestlineGraphRewardsDetailsCustomization::MakeInstance));
	PropertyModule.RegisterCustomClassLayout(UQuestImportMapping::StaticClass()->GetFName(), FOnGetDetailCustomizationInstance::CreateStatic(&FQuestImportMappingDetailsCustomization::MakeInstance));
	PropertyModule.NotifyCustomizationModuleChanged();
	
	FMessageLogModule& MessageLogModule = FModuleManager::LoadModuleChecked<FMessageLogModule>("MessageLog");
	MessageLogModule.RegisterLogListing("QuestCompiler", NSLOCTEXT("SimpleQuestEditor", "QuestCompilerLog", "Quest Compiler"));
	MessageLogModule.RegisterLogListing("QuestValidator", NSLOCTEXT("SimpleQuestEditor", "QuestValidatorLog", "Quest Validator"));
	
#define LOCTEXT_NAMESPACE "SimpleQuestEditor"
	FGlobalTabmanager::Get()->RegisterNomadTabSpawner(
		StaleQuestTagsTabId,
		FOnSpawnTab::CreateRaw(this, &FSimpleQuestEditor::SpawnStaleQuestTagsTab))
		.SetDisplayName(LOCTEXT("StaleQuestTagsTabTitle", "Stale Quest Tags"))
		.SetTooltipText(LOCTEXT("StaleQuestTagsTabTooltip",
			"Lists components in loaded levels whose authored quest-tag fields reference tags no longer registered\n"
			"in the runtime tag manager. Per-row Clear removes the stale tag from the component."))
		.SetGroup(WorkspaceMenu::GetMenuStructure().GetDeveloperToolsDebugCategory())
		.SetMenuType(ETabSpawnerMenuType::Enabled);
#undef LOCTEXT_NAMESPACE

	// The compiled questline tags aren't in the tag tree yet when the startup map deserializes (the authoritative
	// registrar, RegisterTagsFromAssetRegistry, runs later on OnFilesLoaded) — so map/asset load emits a burst of
	// "Invalid GameplayTag SimpleQuest.Questline.*" warnings that LOOK broken but aren't: the tags register moments
	// later and everything resolves; nothing consumes them in the interim. Silence LogGameplayTags for the startup
	// window ONLY, restored in RegisterTagsFromAssetRegistry — so genuine stale-tag warnings still surface afterward.
	// (Root cause is an unresolved config-load quirk on the compiled-tags .ini; see notes blocker A. Time-boxed, not
	// a blanket config mute, which would also hide real stale-tag issues.)
	LogGameplayTags.SetVerbosity(ELogVerbosity::Error);
	
	// ── Tag registration from the compiled INI (deferred past DoneAddingNativeTags) ────────────────────
	// Register the compiled-tags search path after native-tag loading completes (AddTagIniSearchPath must run
	// post-DoneAddingNativeTags, else HandleGameplayTagTreeChanged no-ops but still marks the path added, and the
	// DoneAddingNativeTags self-check then skips the finalizing rebuild). NOTE: this .ini channel does NOT currently
	// materialize tags into the queryable tree at startup — LoadConfig reads zero rows from the compiled .ini for a
	// reason not yet root-caused (see notes blocker A). The authoritative registrar is RegisterTagsFromAssetRegistry
	// -> RebuildNativeTags (on OnFilesLoaded); the stale tag warning flood on startup from this gap is suppressed below.
	const FString CompiledTagsDir = FPaths::GetPath(GetCompiledTagsIniPath());
	UGameplayTagsManager::Get().CallOrRegister_OnDoneAddingNativeTagsDelegate(
		FSimpleMulticastDelegate::FDelegate::CreateLambda([CompiledTagsDir]()
		{
			UGameplayTagsManager::Get().AddTagIniSearchPath(CompiledTagsDir);
			UE_LOG(LogSimpleQuestCompiler, Display, TEXT("Registered compiled-tags search path: %s"), *CompiledTagsDir);
		}));

	MigrateLegacyTagsIni();
	
	FAssetRegistryModule& ARModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
	IAssetRegistry& AR = ARModule.Get();
	
	// Always subscribe — OnFilesLoaded fires when async loading finishes, whenever that is. If the AR is already done loading
	// when we subscribe, the delegate will not fire, so we also call immediately as a fallback for that case.
	AR.OnFilesLoaded().AddRaw(this, &FSimpleQuestEditor::RegisterTagsFromAssetRegistry);
	AR.OnAssetRemoved().AddRaw(this, &FSimpleQuestEditor::OnAssetRemoved);
	if (!AR.IsLoadingAssets())
	{
		RegisterTagsFromAssetRegistry();
	}

	// On UBlueprint load, marks the asset dirty if any FGameplayTag UPROPERTY's value matches a redirect target — a heuristic for
	// "PostSerialize transparently healed this field during load." Save All then writes the healed name to disk, so the asset stops
	// depending on the redirect entry to resolve correctly on future loads.
	OnAssetLoadedHandle = FCoreUObjectDelegates::OnAssetLoaded.AddRaw(this, &FSimpleQuestEditor::MarkDirtyOnRedirectedTagLoad);

	// When changing the filter categories for a tag picker, walks all open blueprints and rebuilds their tag picker trees immediately
	PickerCategoriesChangedHandle = USimpleQuestSettings::OnPickerCategoriesChanged.AddRaw(this, &FSimpleQuestEditor::HandlePickerCategoriesChanged);
	
	// Blueprint compile check requires a fully initialized editor — keep in delegate.
	FEditorDelegates::OnEditorInitialized.AddLambda([this](double)
	{
		const USimpleQuestSettings* Settings = GetDefault<USimpleQuestSettings>();
		FString ClassPath = Settings->QuestManagerClass.ToSoftObjectPath().ToString();
		if (!ClassPath.RemoveFromEnd(TEXT("_C")))
		{
			return;
		}
		UObject* Loaded = StaticLoadObject(UObject::StaticClass(), nullptr, *ClassPath, nullptr, LOAD_NoWarn);
		if (UBlueprint* BP = Cast<UBlueprint>(Loaded))
		{
			if (BP->Status != EBlueprintStatus::BS_UpToDate)
			{
				FKismetEditorUtilities::CompileBlueprint(BP, EBlueprintCompileOptions::SkipGarbageCollection);
				BP->MarkPackageDirty();
			}
		}
	});

	// Register the built-in data-format providers through the public registry — the same interface a studio's provider
	// uses. TSV is the default; JSON is the second built-in. A studio adds its own from its module's StartupModule.
	FQuestDataFormatRegistry::Get().RegisterFormat(TEXT("TSV"),
		FQuestDataFormatFactoryDelegate::CreateLambda([]() -> TUniquePtr<ISimpleQuestDataFormat> { return MakeUnique<FTsvQuestDataFormat>(); }));
	FQuestDataFormatRegistry::Get().RegisterFormat(TEXT("JSON"),
		FQuestDataFormatFactoryDelegate::CreateLambda([]() -> TUniquePtr<ISimpleQuestDataFormat> { return MakeUnique<FJsonQuestDataFormat>(); }));

	// Publish the registered format names to the project setting's dropdown (Project Settings -> Simple Quest ->
	// Resolver). The names live in the editor-only registry; the setting reads them back for its picker.
	USimpleQuestSettings::SetAvailableFormats(FQuestDataFormatRegistry::Get().GetRegisteredNames());
	
	StyleSet = MakeShareable(new FSlateStyleSet("SimpleQuestStyle"));
	StyleSet->SetContentRoot(
		IPluginManager::Get().FindPlugin("SimpleQuest")->GetBaseDir() / TEXT("Resources"));

	StyleSet->Set("ClassThumbnail.QuestlineGraph",
		new FSlateVectorImageBrush(
			StyleSet->RootToContentDir(TEXT("SimpleQuestIconVector64"), TEXT(".svg")),
			FVector2D(64, 64)));

	StyleSet->Set("ClassIcon.QuestlineGraph",
		new FSlateVectorImageBrush(
			StyleSet->RootToContentDir(TEXT("SimpleQuestClassIconWhite16px"), TEXT(".svg")),
			FVector2D(16, 16)));	

	StyleSet->Set("SimpleQuest.Graph.Node.HoverHalo",
	new FSlateBoxBrush(
		StyleSet->RootToContentDir(TEXT("SimpleQuestHoverHalo64"), TEXT(".png")),
		FMargin(18.0f / 64.0f)));

	// Fills for the Source Data panel's banners. The engine's RoundedWarning / RoundedError are OUTLINE ONLY over a
	// transparent fill (StarshipStyle.cpp:511-512), which reads muted against a dark panel. These sit BEHIND
	// SWarningOrErrorBox at the SAME 4px radius so the corners agree, and carry no outline of their own - the widget
	// still draws that, so the engine keeps ownership of the line colour and we only add what it left transparent.
	StyleSet->Set("SimpleQuest.Banner.WarningFill",	new FSlateRoundedBoxBrush(FStyleColors::Warning.GetSpecifiedColor().CopyWithNewOpacity(0.10f), 4.0f));
	StyleSet->Set("SimpleQuest.Banner.ErrorFill", new FSlateRoundedBoxBrush(FStyleColors::Error.GetSpecifiedColor().CopyWithNewOpacity(0.10f), 4.0f));

	FSlateStyleRegistry::RegisterSlateStyle(*StyleSet);

	// PIE debug channel. Subscribes to editor PIE delegates; graph panels query it during OnPaint to drive per-node state overlays.
	// No-op unless PIE is running.
	PIEDebugChannel = MakeUnique<FQuestPIEDebugChannel>();
	PIEDebugChannel->Initialize();

	// Quest State view registration with the generic Facts Panel registry. Each SFactsPanel instance gets its own
	// SQuestStateView via this factory, so per-panel filter / sort / active-tab / scroll state stays isolated across
	// docked panels. Sibling registration to SWorldStateFactsView (registered by SimpleCoreEditor) — both views share
	// the same Facts Panel tab + dropdown.
#define LOCTEXT_NAMESPACE "SimpleQuestEditor"
	FFactsPanelRegistry::Get().RegisterView(
		QuestStateViewId,
		LOCTEXT("QuestStateViewLabel", "Quest State"),
		[](FName PanelPersistenceKey) -> TSharedRef<SWidget>
		{
			return SNew(SQuestStateView).PersistenceKey(PanelPersistenceKey);
		});
#undef LOCTEXT_NAMESPACE
}

FQuestPIEDebugChannel* FSimpleQuestEditor::GetPIEDebugChannel()
{
	if (FSimpleQuestEditor* Module = FModuleManager::GetModulePtr<FSimpleQuestEditor>("SimpleQuestEditor"))
	{
		return Module->PIEDebugChannel.Get();
	}
	return nullptr;
}

void FSimpleQuestEditor::RegisterTagsFromAssetRegistry()
{
	if (bIsRegisteringTags) return;
	TGuardValue<bool> Guard(bIsRegisteringTags, true);

	FAssetRegistryModule* ARModule = FModuleManager::GetModulePtr<FAssetRegistryModule>("AssetRegistry");
	if (!ARModule) return;

	IAssetRegistry& AR = ARModule->Get();

	FARFilter Filter;
	Filter.ClassPaths.Add(UQuestlineGraph::StaticClass()->GetClassPathName());
	Filter.bRecursiveClasses = true;

	TArray<FAssetData> QuestlineAssets;
	AR.GetAssets(Filter, QuestlineAssets);

	UE_LOG(LogSimpleQuestCompiler, Display, TEXT("SimpleQuestEditor: RegisterTagsFromAssetRegistry — found %d questline asset(s)"), QuestlineAssets.Num());

	for (const FAssetData& AssetData : QuestlineAssets)
	{
		FAssetTagValueRef TagValue = AssetData.TagsAndValues.FindTag(TEXT("CompiledQuestTags"));
		if (!TagValue.IsSet() || TagValue.GetValue().IsEmpty())
		{
			UE_LOG(LogSimpleQuestCompiler, Display, TEXT("  %s — no CompiledQuestTags metadata (not yet compiled+saved)"), *AssetData.AssetName.ToString());
			continue;
		}

		TArray<FString> TagStrings;
		TagValue.GetValue().ParseIntoArray(TagStrings, TEXT("|"), true);

		TArray<FName> TagNames;
		TagNames.Reserve(TagStrings.Num());
		for (const FString& TagStr : TagStrings)
		{
			TagNames.Add(FName(*TagStr));
		}

		CompiledTagRegistry.Add(AssetData.PackageName.ToString(), MoveTemp(TagNames));
		UE_LOG(LogSimpleQuestCompiler, Display, TEXT("  %s — loaded %d tag(s)"), *AssetData.AssetName.ToString(), TagStrings.Num());
	}
	
	// The INI is the authoritative compiled state. Only generate it from AR metadata when it doesn't already exist (first
	// run, deleted file). After that it is exclusively maintained by RegisterCompiledTags at compile time. Writing it unconditionally
	// here would overwrite a correctly-compiled INI with stale AR metadata whenever a graph was compiled but not saved.
	const FString IniPath = GetCompiledTagsIniPath();
	if (!FPaths::FileExists(IniPath))
	{
		WriteCompiledTagsIni();
	}
	RebuildNativeTags();

	// Tags are now registered — restore normal gameplay-tag logging (fires on OnFilesLoaded, after the startup map's
	// benign Invalid-tag burst). Real stale-tag warnings surface normally for the rest of the session. See StartupModule.
	LogGameplayTags.SetVerbosity(ELogVerbosity::All);
	UE_LOG(LogSimpleQuestCompiler, Display, TEXT("SimpleQuestEditor: tag registration complete (%d graph(s) in registry)"), CompiledTagRegistry.Num());
}

void FSimpleQuestEditor::OnAssetRemoved(const FAssetData& AssetData)
{
	if (AssetData.AssetClassPath != UQuestlineGraph::StaticClass()->GetClassPathName()) return;

	const FString RemovedPath = AssetData.PackageName.ToString();
	TArray<FName> RemovedTags;
	if (CompiledTagRegistry.RemoveAndCopyValue(RemovedPath, RemovedTags))
	{
		UE_LOG(LogSimpleQuestCompiler, Display, TEXT("FSimpleQuestEditor::OnAssetRemoved — removed %s from tag registry, rewriting INI"), *AssetData.AssetName.ToString());
		WriteCompiledTagsIni();
		// Surgical: unregister only this graph's now-orphaned tags. RemoveAndCopyValue already dropped it from the
		// registry, so the "still claimed by another" check sees the correct remaining set.
		RemoveNativeTagsForGraph(RemovedTags);
	}
	RemoveCompiledDisplaySection(AssetData.GetTagValueRef<FString>(TEXT("QuestlineEffectiveID")));
}

void FSimpleQuestEditor::ShutdownModule()
{
	FEditorDelegates::MapChange.RemoveAll(this);

	FQuestDataFormatRegistry::Get().Reset();

	if (PIEDebugChannel.IsValid())
	{
		PIEDebugChannel->Shutdown();
		PIEDebugChannel.Reset();
	}

	FFactsPanelRegistry::Get().UnregisterView(QuestStateViewId);
	
	if (FModuleManager::Get().IsModuleLoaded("AssetRegistry"))
	{
		FModuleManager::GetModuleChecked<FAssetRegistryModule>("AssetRegistry").Get().OnFilesLoaded().RemoveAll(this);
		FModuleManager::GetModuleChecked<FAssetRegistryModule>("AssetRegistry").Get().OnAssetRemoved().RemoveAll(this);
	}

	FCoreUObjectDelegates::OnAssetLoaded.Remove(OnAssetLoadedHandle);

	USimpleQuestSettings::OnPickerCategoriesChanged.Remove(PickerCategoriesChangedHandle);
	
	if (FSlateApplication::IsInitialized())
	{
		FGlobalTabmanager::Get()->UnregisterNomadTabSpawner(StaleQuestTagsTabId);
	}
	
	if (FModuleManager::Get().IsModuleLoaded("MessageLog"))
	{
		FMessageLogModule& MessageLogModule = FModuleManager::GetModuleChecked<FMessageLogModule>("MessageLog");
		MessageLogModule.UnregisterLogListing("QuestValidator");
		MessageLogModule.UnregisterLogListing("QuestCompiler");
	}

	if (FModuleManager::Get().IsModuleLoaded("PropertyEditor"))
	{
		FPropertyEditorModule& PropertyModule = FModuleManager::GetModuleChecked<FPropertyEditorModule>("PropertyEditor");
		PropertyModule.UnregisterCustomClassLayout(UQuestlineNode_Entry::StaticClass()->GetFName());
		PropertyModule.UnregisterCustomClassLayout(UQuestlineGraph::StaticClass()->GetFName());
		PropertyModule.UnregisterCustomClassLayout(UQuestImportMapping::StaticClass()->GetFName());
	}
	
	FQuestlineGraphEditorCommands::Unregister();

	if (StyleSet.IsValid())
	{
		FSlateStyleRegistry::UnRegisterSlateStyle(*StyleSet);
		StyleSet.Reset();
	}
	if (FModuleManager::Get().IsModuleLoaded("AssetTools"))
	{
		IAssetTools& AssetTools = FModuleManager::GetModuleChecked<FAssetToolsModule>("AssetTools").Get();
		AssetTools.UnregisterAssetTypeActions(QuestlineGraphAssetTypeActions.ToSharedRef());
	}
	
	FEdGraphUtilities::UnregisterVisualNodeFactory(QuestlineGraphNodeFactory);
	QuestlineGraphNodeFactory.Reset();

	FEdGraphUtilities::UnregisterVisualPinConnectionFactory(QuestlineConnectionFactory);
	QuestlineConnectionFactory.Reset();
	
	QuestlineGraphAssetTypeActions.Reset();
}

void FSimpleQuestEditor::RegisterCompilerFactory(FQuestlineCompilerFactoryDelegate InFactory)
{
	CompilerFactory = MoveTemp(InFactory);
}

void FSimpleQuestEditor::UnregisterCompilerFactory()
{
	CompilerFactory.Unbind();
}

TUniquePtr<FQuestlineGraphCompiler> FSimpleQuestEditor::CreateCompiler() const
{
	if (CompilerFactory.IsBound())
	{
		TUniquePtr<FQuestlineGraphCompiler> CustomCompiler = CompilerFactory.Execute();
		if (CustomCompiler.IsValid())
		{
			return CustomCompiler;
		}
		UE_LOG(LogTemp, Warning, TEXT("FSimpleQuestEditor::CreateCompiler : Registered factory returned null. Falling back to default compiler."));
	}
	return MakeUnique<FQuestlineGraphCompiler>();
}

void FSimpleQuestEditor::RegisterCompiledTags(const FString& GraphPath, const TArray<FName>& TagNames)
{
	// Collect the names this recompile DROPPED (present in the old registration, absent from the new) so removal can be
	// surgical instead of a full teardown.
	TArray<FName> StaleNames;
	if (const TArray<FName>* OldTags = CompiledTagRegistry.Find(GraphPath))
	{
		TSet<FName> NewTagSet(TagNames);
		for (const FName& OldTag : *OldTags)
		{
			if (!NewTagSet.Contains(OldTag))
			{
				StaleNames.Add(OldTag);
				UE_LOG(LogSimpleQuestCompiler, Display, TEXT("  Stale tag removed: %s"), *OldTag.ToString());
			}
		}
	}
	const bool bHasStaleTags = StaleNames.Num() > 0;

	UE_LOG(LogSimpleQuestCompiler, Display, TEXT("FSimpleQuestEditor::RegisterCompiledTags — %s (%d tag(s)%s%s)"),
		*GraphPath, TagNames.Num(),
		bHasStaleTags ? TEXT(", stale tags cleaned") : TEXT(""),
		bBatchActive ? TEXT(", batched") : TEXT(""));

	CompiledTagRegistry.Add(GraphPath, TagNames);

	if (bBatchActive)
	{
		// Register new natives incrementally so mid-batch RequestGameplayTag lookups succeed; accumulate stale names for
		// ONE surgical removal at EndCompileBatch (a name stale-from-graph-A but re-added-by-graph-B nets out correctly
		// there, because RemoveNativeTagsForGraph checks the batch-final registry).
		BatchStaleNames.Append(StaleNames);
		AddNativeTagsForGraph(TagNames);
		return;
	}

	WriteCompiledTagsIni();
	AddNativeTagsForGraph(TagNames);        // register new/kept natives (skips already-registered)
	if (bHasStaleTags)
	{
		RemoveNativeTagsForGraph(StaleNames);   // prunes orphans + refreshes the tree
	}
	else
	{
		UGameplayTagsManager::Get().ConstructGameplayTagTree();   // adds-only: fold new natives into the tree
	}
}

void FSimpleQuestEditor::BeginCompileBatch()
{
	check(!bBatchActive);
	bBatchActive = true;
	bBatchHasStaleTags = false;
	bBatchAddedNewTag = false;
	BatchStaleNames.Reset();
}

void FSimpleQuestEditor::EndCompileBatch()
{
	if (!bBatchActive) return;
	bBatchActive = false;

	WriteCompiledTagsIni();
	FlushCompiledDisplayIni();

	// Tree rebuild path. Three cases, cheapest-first:
	//   - Stale tags removed -> full reset+refresh (must PRUNE the removed tags from the tree).
	//   - New tags added (no stale) -> ConstructGameplayTagTree to fold the incrementally-added natives into the tree.
	//   - NOTHING changed (no new, no stale — e.g. a re-import/recompile of already-registered content) -> SKIP the
	//     tree rebuild entirely. The tree already contains exactly these tags; rebuilding pure redundant work.
	//     This is the common case for the round-trip harness + any recompile of unchanged content.
	if (BatchStaleNames.Num() > 0)
	{
		// Surgical prune of the batch's orphaned tags (checks the batch-FINAL registry, so a name dropped by one graph
		// but re-added by another nets to "kept"). RemoveNativeTagsForGraph does the one tree refresh. If it finds no
		// true orphans but new tags were added, still need to fold those in.
		const TArray<FName> StaleArray = BatchStaleNames.Array();
		RemoveNativeTagsForGraph(StaleArray);
		if (bBatchAddedNewTag)
		{
			UGameplayTagsManager::Get().ConstructGameplayTagTree();   // ensure adds are folded in even if remove was a no-op
		}
	}
	else if (bBatchAddedNewTag)
	{
		UGameplayTagsManager::Get().ConstructGameplayTagTree();
	}
	// else: tag set unchanged -> tree already correct -> no rebuild.

	bBatchHasStaleTags = false;
	bBatchAddedNewTag = false;
	BatchStaleNames.Reset();
}

void FSimpleQuestEditor::CompileAllQuestlineGraphs()
{
    IAssetRegistry& AR = FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry").Get();

    FARFilter Filter;
    Filter.ClassPaths.Add(UQuestlineGraph::StaticClass()->GetClassPathName());
    Filter.bRecursiveClasses = true;

    TArray<FAssetData> QuestlineAssets;
    AR.GetAssets(Filter, QuestlineAssets);

    if (QuestlineAssets.IsEmpty())
    {
        // Notification: "No questline graphs found."
        return;
    }

    FScopedSlowTask SlowTask(QuestlineAssets.Num(), NSLOCTEXT("SimpleQuestEditor", "CompileAll_Progress", "Compiling questline graphs..."));
    SlowTask.MakeDialog(/*bShowCancelButton=*/ true);

	int32 SuccessCount = 0;
	int32 FailCount = 0;
	int32 TotalErrors = 0;
	int32 TotalWarnings = 0;
	FMessageLog CompilerLog("QuestCompiler");
	CompilerLog.NewPage(NSLOCTEXT("SimpleQuestEditor", "CompileAllPageLabel", "Compile All"));

	int32 TotalRenamedActors = 0;
	TMap<FName, FName> AllRenames;

	// Single batch covers all per-graph compiles + the one coalesced WriteGameplayTagRedirects call. Native-tag registrations
	// queued by RegisterCompiledTags during each Compile() flush in EndCompileBatch's RebuildNativeTags — fired AFTER the
	// redirect write below — so rebuilt tags register under the new redirect map, not the pre-rename one. ON_SCOPE_EXIT covers
	// early-return / SlowTask cancel paths.
	{
		BeginCompileBatch();
		ON_SCOPE_EXIT { EndCompileBatch(); };

		for (const FAssetData& AssetData : QuestlineAssets)
		{
			if (SlowTask.ShouldCancel()) break;

			SlowTask.EnterProgressFrame(1.f, FText::Format(NSLOCTEXT("SimpleQuestEditor", "CompileAll_Item", "Compiling {0}..."), FText::FromName(AssetData.AssetName)));

			UQuestlineGraph* Graph = Cast<UQuestlineGraph>(AssetData.GetAsset());
			if (!Graph) { ++FailCount; continue; }

			TUniquePtr<FQuestlineGraphCompiler> Compiler = CreateCompiler();
			const bool bSuccess = Compiler->Compile(Graph);

			// Capture rename intent regardless of compile success. Renames are detected via the GUID bridge — a
			// structural property of the graph that's valid whether or not unrelated nodes failed validation in
			// the same compile. Gating behind success silently drops the rename when ANY error fires elsewhere
			// in the graph: RegisterCompiledTags still registers the new tag (so the picker updates), but the
			// OldName → NewName redirect never lands, and loaded actor instances keep their stale tags with
			// nothing in the redirect map to heal them. Different graphs producing the same (OldName → NewName)
			// pair (shared LinkedQuestline targets) merge cleanly; TMap::Append's second-wins behavior is a
			// no-op for identical values.
			AllRenames.Append(Compiler->GetDetectedRenames());

			if (bSuccess)
			{
				++SuccessCount;
				AccumulateCompiledDisplay(Graph);   // in-memory; coalesced to one ini write in EndCompileBatch

				UPackage* Package = Graph->GetOutermost();
				Package->MarkPackageDirty();
				FSavePackageArgs Args;
				UPackage::SavePackage(Package, Graph, *FPackageName::LongPackageNameToFilename(Package->GetName(), FPackageName::GetAssetPackageExtension()), Args);
				QuestlineCompiledDelegate.Broadcast(Package->GetName(), true);
			}
			else
			{
				++FailCount;
				QuestlineCompiledDelegate.Broadcast(Graph->GetOutermost()->GetName(), false);
			}

			if (Compiler->GetMessages().Num() > 0)
			{
				CompilerLog.AddMessages(Compiler->GetMessages());
				TotalErrors += Compiler->GetNumErrors();
				TotalWarnings += Compiler->GetNumWarnings();
			}
		}

		// One coalesced redirect write for the entire batch, inside the scope so EndCompileBatch's RebuildNativeTags fires AFTER
		// the CDO + manager-redirect-map are current. Native tags then re-register under the new redirects in a single rebuild.
		if (AllRenames.Num() > 0)
		{
			FSimpleQuestEditorUtilities::WriteGameplayTagRedirects(AllRenames);
		}
	}

	// Swap helpers run AFTER the batch closes — the tag tree reflects the new redirects and the new canonical names are registered
	// as themselves, so RequestGameplayTag lookups inside the helpers return valid tags rather than silently clearing adopter data.
	if (AllRenames.Num() > 0)
	{
		TotalRenamedActors = FSimpleQuestEditorUtilities::ApplyTagRenamesToLoadedWorlds(AllRenames);
		FSimpleQuestEditorUtilities::ApplyTagRenamesToLoadedBlueprintCDOs(AllRenames);
		FSimpleQuestEditorUtilities::ApplyTagRenamesToLoadedAssets(AllRenames);
	}

    // Summary notification
    if (TotalErrors > 0 || TotalWarnings > 0)
    {
        // Clickable toast — opens the MessageLog with all per-graph pages
        CompilerLog.Notify(FText::Format(NSLOCTEXT("SimpleQuestEditor", "CompileAll_Issues", "Compiled {0} questline(s): {1} error(s), {2} warning(s)"),
            FText::AsNumber(SuccessCount + FailCount),
            FText::AsNumber(TotalErrors),
            FText::AsNumber(TotalWarnings)));
    }
    else
    {
        // Clean run — simple success toast
        const FText Summary = FText::Format(NSLOCTEXT("SimpleQuestEditor", "CompileAll_Summary", "Compiled {0} questline(s) successfully"), FText::AsNumber(SuccessCount + FailCount));
        FNotificationInfo Info(Summary);
        Info.ExpireDuration = 5.f;
        Info.bUseSuccessFailIcons = true;
        FSlateNotificationManager::Get().AddNotification(Info)->SetCompletionState(SNotificationItem::CS_Success);
    }

	// Tag rename toast
	if (AllRenames.Num() > 0)
	{
		FNotificationInfo RenameInfo(FText::Format(NSLOCTEXT("SimpleQuestEditor", "CompileAll_TagRenames", "{0} tag(s) renamed. {1} actor(s) updated in loaded levels."), AllRenames.Num(), TotalRenamedActors));
		RenameInfo.ExpireDuration = 5.f;
		RenameInfo.bUseSuccessFailIcons = true;
		FSlateNotificationManager::Get().AddNotification(RenameInfo)->SetCompletionState(SNotificationItem::CS_Success);
	}
}

namespace
{
    /** Walks an asset's editor graph (recursive through Quest inner graphs) and collects every LinkedGraph target
     it finds on LinkedQuestline nodes. Reads in-memory authoring state — current, not last-saved. */
    static void CollectLinkedQuestlineTargets(UQuestlineGraph* Asset, TSet<UQuestlineGraph*>& OutTargets)
    {
        if (!Asset || !Asset->QuestlineEdGraph) return;

        TFunction<void(UEdGraph*)> Walk;
        Walk = [&](UEdGraph* Graph)
        {
            if (!Graph) return;
            for (UEdGraphNode* Node : Graph->Nodes)
            {
                if (UQuestlineNode_LinkedQuestline* LinkedNode = Cast<UQuestlineNode_LinkedQuestline>(Node))
                {
                    if (!LinkedNode->LinkedGraph.IsNull())
                    {
                        // LoadSynchronous resolves the soft-ref; typically a no-op in editor since the target is resident.
                        if (UQuestlineGraph* Target = LinkedNode->LinkedGraph.LoadSynchronous())
                        {
                            OutTargets.Add(Target);
                        }
                    }
                }
                else if (UQuestlineNode_Quest* QuestNode = Cast<UQuestlineNode_Quest>(Node))
                {
                    Walk(QuestNode->GetInnerGraph());
                }
            }
        };

        Walk(Asset->QuestlineEdGraph);
    }
}

void FSimpleQuestEditor::CollectLinkedNeighborhood(UQuestlineGraph* Primary, TArray<UQuestlineGraph*>& OutNeighborhood) const
{
    OutNeighborhood.Reset();
    if (!Primary) return;

    // Walks in-memory node graphs rather than AR dependencies. AR's package dependency graph is rebuilt from the
    // package ImportTable on save; it lags in-memory LinkedQuestline edits (add/remove/retarget) until the package
    // is written to disk. Scanning authored nodes directly reflects current state.
    IAssetRegistry& AR = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry")).Get();
    TArray<FAssetData> QuestlineAssets;
    AR.GetAssetsByClass(UQuestlineGraph::StaticClass()->GetClassPathName(), QuestlineAssets);

    // Forward-ref index: source asset → set of assets it LinkedQuestlines into (from in-memory authoring).
    // O(total assets × nodes per asset) — matches the cost profile of CollectActivationGroupTopology.
    TMap<UQuestlineGraph*, TSet<UQuestlineGraph*>> ForwardRefs;
    for (const FAssetData& Data : QuestlineAssets)
    {
        UQuestlineGraph* Asset = Cast<UQuestlineGraph>(Data.GetAsset()); // sync-load if not resident
        if (!Asset) continue;

        TSet<UQuestlineGraph*> Targets;
        CollectLinkedQuestlineTargets(Asset, Targets);
        if (Targets.Num() > 0)
        {
            ForwardRefs.Add(Asset, MoveTemp(Targets));
        }
    }

    // Transitive BFS from Primary, bidirectional. Primary pre-seeded into Visited so it's never an output entry.
    TSet<UQuestlineGraph*> Visited;
    Visited.Add(Primary);

    TArray<UQuestlineGraph*> Frontier;
    Frontier.Add(Primary);

    while (Frontier.Num() > 0)
    {
        UQuestlineGraph* Current = Frontier.Pop(EAllowShrinking::No);

        // Forward: assets Current references via LinkedQuestline.
        if (const TSet<UQuestlineGraph*>* CurrentTargets = ForwardRefs.Find(Current))
        {
            for (UQuestlineGraph* Target : *CurrentTargets)
            {
                if (!Target || Visited.Contains(Target)) continue;
                Visited.Add(Target);
                Frontier.Add(Target);
                OutNeighborhood.Add(Target);
            }
        }

        // Backward: assets that reference Current. Scan the forward map for Current as a target.
        for (const auto& [Source, Targets] : ForwardRefs)
        {
            if (!Source || Visited.Contains(Source)) continue;
            if (Targets.Contains(Current))
            {
                Visited.Add(Source);
                Frontier.Add(Source);
                OutNeighborhood.Add(Source);
            }
        }
    }

    if (UE_LOG_ACTIVE(LogSimpleQuestCompiler, Verbose))
    {
        TStringBuilder<256> NeighborList;
        for (int32 i = 0; i < OutNeighborhood.Num(); ++i)
        {
            if (i > 0) NeighborList << TEXT(", ");
            NeighborList << OutNeighborhood[i]->GetName();
        }
        UE_LOG(LogSimpleQuestCompiler, Verbose, TEXT("CollectLinkedNeighborhood: Primary '%s' → %d linked asset(s) [%s]"),
            *Primary->GetName(), OutNeighborhood.Num(), *FString(NeighborList));
    }
}

bool FSimpleQuestEditor::CompileQuestlineAndNeighborhood(UQuestlineGraph* Primary, int32& OutCompiledCount)
{
	OutCompiledCount = 0;
	if (!Primary) { return false; }

	bool bAllSucceeded = true;
	TMap<FName, FName> AllRenames;

	// Single batch covers the primary + every linked neighbor + the coalesced WriteGameplayTagRedirects call, so the
	// gameplay-tag tree rebuilds ONCE at EndCompileBatch rather than per graph. ON_SCOPE_EXIT so an early return can
	// never leave the batch open. Same sequencing as the editor's Compile action and CompileAllQuestlineGraphs.
	{
		BeginCompileBatch();
		ON_SCOPE_EXIT { EndCompileBatch(); };

		auto CompileOne = [&](UQuestlineGraph* Graph)
		{
			if (!Graph) { return; }
			TUniquePtr<FQuestlineGraphCompiler> Compiler = CreateCompiler();
			const bool bSuccess = Compiler->Compile(Graph);

			// Rename intent is captured regardless of success: renames come from the GUID bridge, a structural property
			// that holds whether or not unrelated nodes failed validation in the same compile. Gating on success would
			// register the new tag but never write the redirect, stranding loaded actors on stale tags.
			AllRenames.Append(Compiler->GetDetectedRenames());

			if (bSuccess) { AccumulateCompiledDisplay(Graph); }
			else          { bAllSucceeded = false; }
			++OutCompiledCount;
		};

		CompileOne(Primary);

		TArray<UQuestlineGraph*> Neighborhood;
		CollectLinkedNeighborhood(Primary, Neighborhood);
		for (UQuestlineGraph* Neighbor : Neighborhood) { CompileOne(Neighbor); }

		// Inside the batch scope so EndCompileBatch's RebuildNativeTags fires AFTER the redirect map is written and
		// rebuilt tags register under the new names rather than the pre-rename ones.
		if (AllRenames.Num() > 0)
		{
			FSimpleQuestEditorUtilities::WriteGameplayTagRedirects(AllRenames);
		}
	}

	return bAllSucceeded;
}

void FSimpleQuestEditor::MigrateLegacyTagsIni()
{
	// Two prior locations to clean up on upgrade, both written by older versions of this module before the current
	// plugin-local destination was adopted. Either being present at startup indicates the project hasn't been
	// recompiled since the upgrade; the next Compile All Questlines pass writes to the new plugin location.
	const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("SimpleQuest"));
	TArray<FString> LegacyPaths = {
		FPaths::ConvertRelativePathToFull(FPaths::ProjectConfigDir() / TEXT("Tags/SimpleQuestCompiledTags.ini")),
		FPaths::ConvertRelativePathToFull(FPaths::ProjectConfigDir() / TEXT("SimpleQuest/CompiledTags.ini")),
	};
	if (Plugin.IsValid())   // the previous plugin-local destination, superseded by the project-local path
	{
		LegacyPaths.Add(FPaths::ConvertRelativePathToFull(Plugin->GetBaseDir() / TEXT("Config/Tags/SimpleQuestCompiledTags.ini")));
	}

	for (const FString& LegacyPath : LegacyPaths)
	{
		if (FPaths::FileExists(LegacyPath))
		{
			IFileManager::Get().Delete(*LegacyPath);
			UE_LOG(LogSimpleQuestCompiler, Display,
				TEXT("MigrateLegacyTagsIni — deleted legacy INI at '%s'. Tags now managed via plugin Config/Tags/."),
				*LegacyPath);
		}
	}
}

void FSimpleQuestEditor::WriteCompiledTagsIni() const
{
    const FString IniPath = GetCompiledTagsIniPath();

    // Collect compiled tags and state facts from registry
    TArray<FName> AllTags;
	for (const auto& Pair : CompiledTagRegistry)
	{
		for (const FName& QuestTag : Pair.Value)
		{
			// Defensive: skip NAME_None entries that occasionally leak into CompiledQuestTags AR metadata
			// (orphan nodes, failed tag assignment in upstream compile). Without this guard we emit
			// "None.Live" / "None.Blocked" etc. into CompiledTags.ini.
			if (QuestTag.IsNone()) continue;

			AllTags.Add(QuestTag);
			
			if (FQuestTagComposer::IsIdentityTag(QuestTag))
			{
				for (EQuestStateLeaf Leaf : FQuestTagComposer::AllStateLeaves)
				{
					AllTags.Add(FQuestTagComposer::MakeStateFact(QuestTag, Leaf));
				}
			}
		}
	}

    // Deduplicate and sort
    AllTags.Sort([](const FName& A, const FName& B) { return A.LexicalLess(B); });
    {
        int32 WriteIdx = 0;
        for (int32 ReadIdx = 0; ReadIdx < AllTags.Num(); ++ReadIdx)
        {
	        if (ReadIdx == 0 || AllTags[ReadIdx] != AllTags[WriteIdx - 1])
	        {
	        	AllTags[WriteIdx++] = AllTags[ReadIdx];
	        }
        }
        AllTags.SetNum(WriteIdx);
    }

    FString IniContent;
    IniContent.Reserve(AllTags.Num() * 80 + 512);
    IniContent += TEXT("; ==========================================================================\n");
    IniContent += TEXT("; AUTO-GENERATED by SimpleQuest compiler. DO NOT EDIT.\n");
    IniContent += TEXT(";\n");
    IniContent += TEXT("; Overwritten on every compile. Manual edits will be lost.\n");
    IniContent += TEXT("; For custom gameplay tags, use Config/Tags/DefaultGameplayTags.ini.\n");
    IniContent += TEXT("; ==========================================================================\n");
    IniContent += TEXT("[/Script/GameplayTags.GameplayTagsList]\n");
    for (const FName& TagName : AllTags)
    {
        IniContent += FString::Printf(TEXT("+GameplayTagList=(Tag=\"%s\",DevComment=\"SimpleQuest\")\n"), *TagName.ToString());
    }

    const FString IniDir = FPaths::GetPath(IniPath);
    if (!IFileManager::Get().DirectoryExists(*IniDir))
    {
        IFileManager::Get().MakeDirectory(*IniDir, true);
    }

	if (FFileHelper::SaveStringToFile(IniContent, *IniPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
    {
        UE_LOG(LogSimpleQuestCompiler, Display, TEXT("FSimpleQuestEditor::WriteCompiledTagsIni — wrote %d tag(s) to: %s"), AllTags.Num(), *IniPath);
    }
    else
    {
        UE_LOG(LogSimpleQuestCompiler, Error, TEXT("FSimpleQuestEditor::WriteCompiledTagsIni — write FAILED for: %s"), *IniPath);
    }
}


FString FSimpleQuestEditor::GetCompiledDisplayIniPath()
{
	// Same project-local home as the compiled-tags ini (see GetCompiledTagsIniPath) — generated, per-project data
	// lives with the consuming project, not the plugin folder, so an engine-installed plugin stays writable/isolated.
	return FPaths::ConvertRelativePathToFull(FPaths::ProjectConfigDir() / TEXT("SimpleQuest/SimpleQuestCompiledDisplay.ini"));
}

void FSimpleQuestEditor::AccumulateCompiledDisplay(const UQuestlineGraph* Graph)
{
	if (!Graph) return;
	PendingDisplaySections.Add(Graph->GetEffectiveID(), Graph->GetCompiledDisplayRecords());
	if (!bBatchActive) FlushCompiledDisplayIni();   // non-batched compile: write through immediately
}

void FSimpleQuestEditor::FlushCompiledDisplayIni()
{
	if (PendingDisplaySections.Num() == 0) return;
	const FString IniPath = GetCompiledDisplayIniPath();

	FString Existing;
	FFileHelper::LoadFileToString(Existing, *IniPath);                       // one read
	TMap<FString, TArray<FString>> Sections = ParseDisplaySections(Existing);

	// Apply only the sections this batch touched — replace if it has records, drop it if the graph lost all display data.
	for (TPair<FString, TArray<FString>>& Pending : PendingDisplaySections)
	{
		if (Pending.Value.Num() > 0) { Sections.FindOrAdd(Pending.Key) = MoveTemp(Pending.Value); }
		else                         { Sections.Remove(Pending.Key); }
	}

	WriteSectionsToDisk(IniPath, Sections);                                  // one write
	UE_LOG(LogSimpleQuestCompiler, Display, TEXT("FlushCompiledDisplayIni — %d section(s) coalesced → %s"), PendingDisplaySections.Num(), *IniPath);
	PendingDisplaySections.Empty();
}

void FSimpleQuestEditor::RemoveCompiledDisplaySection(const FString& EffectiveID) const
{
	const FString IniPath = GetCompiledDisplayIniPath();
	FString Existing;
	if (!FFileHelper::LoadFileToString(Existing, *IniPath)) return;
	TMap<FString, TArray<FString>> Sections = ParseDisplaySections(Existing);
	if (Sections.Remove(EffectiveID) > 0) { WriteSectionsToDisk(IniPath, Sections); }
}

void FSimpleQuestEditor::RebuildNativeTags(bool bRefreshTree)
{
	// Full reset: tear down all FNativeGameplayTags (each destructor unregisters from the manager),
	// then re-add via the shared helper. Used in non-batch single-graph compile and in EndCompileBatch
	// when stale tags need to be pruned from the tree.
	CompiledNativeTags.Reset();
	CompiledNativeTagNames.Reset();

	for (const auto& Pair : CompiledTagRegistry)
	{
		AddNativeTagsForGraph(Pair.Value);
	}

	if (bRefreshTree)
	{
		UGameplayTagsManager::Get().EditorRefreshGameplayTagTree();
	}
	else
	{
		UGameplayTagsManager::Get().ConstructGameplayTagTree();
	}

	UE_LOG(LogSimpleQuestCompiler, Display, TEXT("FSimpleQuestEditor::RebuildNativeTags — registered %d native tag(s)%s"),
		CompiledNativeTags.Num(),
		bRefreshTree ? TEXT(" (tree refreshed)") : TEXT(""));
}

namespace
{
	// Recursive detection walk — returns true on first field whose value is in RedirectTargets. Recurses into nested
	// USTRUCT fields. Cycle-free (no by-value struct self-references in UE). Mirrors ApplyTagRenamesToStructLayout in
	// shape — the apply path and the detect path walk the same structural territory.
	bool HasFieldMatchingRedirectTarget(const UStruct* Struct, const void* ContainerPtr, const TSet<FName>& RedirectTargets)
	{
		if (!Struct || !ContainerPtr) return false;

		for (TFieldIterator<FStructProperty> PropIt(Struct); PropIt; ++PropIt)
		{
			FStructProperty* StructProp = *PropIt;

			if (StructProp->Struct == FGameplayTag::StaticStruct())
			{
				const FGameplayTag* TagPtr = StructProp->ContainerPtrToValuePtr<FGameplayTag>(ContainerPtr);
				if (TagPtr && RedirectTargets.Contains(TagPtr->GetTagName())) return true;
			}
			else if (StructProp->Struct == FGameplayTagContainer::StaticStruct())
			{
				const FGameplayTagContainer* ContainerProp = StructProp->ContainerPtrToValuePtr<FGameplayTagContainer>(ContainerPtr);
				if (ContainerProp)
				{
					for (const FGameplayTag& Tag : *ContainerProp)
					{
						if (RedirectTargets.Contains(Tag.GetTagName())) return true;
					}
				}
			}
			else
			{
				const void* NestedPtr = StructProp->ContainerPtrToValuePtr<void>(ContainerPtr);
				if (HasFieldMatchingRedirectTarget(StructProp->Struct, NestedPtr, RedirectTargets)) return true;
			}
		}
		return false;
	}
}

void FSimpleQuestEditor::MarkDirtyOnRedirectedTagLoad(UObject* LoadedAsset)
{
	if (!LoadedAsset) return;

	UGameplayTagsSettings* Settings = GetMutableDefault<UGameplayTagsSettings>();
	if (!Settings || Settings->GameplayTagRedirects.Num() == 0) return;

	// Decide where the FGameplayTag fields live. UBlueprint loads expose them on the generated-class CDO; other asset types
	// (UDataAsset / UDataTable / adopter custom asset classes) hold them on the asset object itself.
	UObject* InspectionTarget = LoadedAsset;
	if (UBlueprint* BP = Cast<UBlueprint>(LoadedAsset))
	{
		if (!BP->GeneratedClass) return;
		UObject* CDO = BP->GeneratedClass->GetDefaultObject(/*bCreateIfNeeded*/ false);
		if (!CDO) return;
		InspectionTarget = CDO;
	}

	// Build a set of every NewTagName in the active redirect map. A field that holds one of these names AFTER deserialization
	// MAY have been transparently rewritten by FGameplayTag::PostSerialize from a corresponding OldTagName on disk. We can't
	// distinguish "redirected on load" from "always had this name" without comparing to the on-disk bytes — the heuristic accepts
	// occasional no-op saves in exchange for catching the real cases.
	TSet<FName> RedirectTargets;
	RedirectTargets.Reserve(Settings->GameplayTagRedirects.Num());
	for (const FGameplayTagRedirect& Entry : Settings->GameplayTagRedirects)
	{
		RedirectTargets.Add(Entry.NewTagName);
	}

	bool bMatched = HasFieldMatchingRedirectTarget(InspectionTarget->GetClass(), InspectionTarget, RedirectTargets);

	// UDataTable special case: rows live in TMap<FName, uint8*> RowMap with layout described by RowStruct. The walk above
	// only sees UDataTable's own UPROPERTYs, not the row data behind the map.
	if (!bMatched)
	{
		if (UDataTable* DataTable = Cast<UDataTable>(InspectionTarget))
		{
			if (const UScriptStruct* RowStruct = DataTable->RowStruct)
			{
				for (const TPair<FName, uint8*>& RowPair : DataTable->GetRowMap())
				{
					if (!RowPair.Value) continue;
					if (HasFieldMatchingRedirectTarget(RowStruct, RowPair.Value, RedirectTargets))
					{
						bMatched = true;
						break;
					}
				}
			}
		}
	}

	if (bMatched)
	{
		// UPackage::MarkPackageDirty silently no-ops while UE is routing PostLoad calls — OnAssetLoaded fires from inside that phase,
		// so a direct mark here is suppressed by design (UE doesn't want load-time changes to flag assets as user-modified). Defer to
		// the next tick to escape the routing context. The mark goes on the loaded asset (what UE will serialize), regardless of
		// whether the matching field lived on the asset directly or on its generated-class CDO.
		TWeakObjectPtr<UObject> WeakAsset(LoadedAsset);
		FTSTicker::GetCoreTicker().AddTicker(FTickerDelegate::CreateLambda([WeakAsset](float)
		{
			if (UObject* DeferredAsset = WeakAsset.Get())
			{
				DeferredAsset->MarkPackageDirty();
				UE_LOG(LogSimpleQuestCompiler, Verbose,
					TEXT("MarkDirtyOnRedirectedTagLoad: deferred dirty mark fired for '%s' (%s) — Save All will now catch the healed FGameplayTag value(s)"),
					*DeferredAsset->GetName(), *DeferredAsset->GetClass()->GetName());
			}
			return false; // one-shot — unregister after firing
		}), 0.0f);
	}
}

TSharedRef<SDockTab> FSimpleQuestEditor::SpawnStaleQuestTagsTab(const FSpawnTabArgs& Args)
{
	return SNew(SDockTab)
		.TabRole(ETabRole::NomadTab)
		[
			SNew(SStaleQuestTagsPanel)
		];
}

void FSimpleQuestEditor::AddNativeTagsForGraph(const TArray<FName>& TagNames)
{
	UGameplayTagsManager& TagsManager = UGameplayTagsManager::Get();

	for (const FName& QuestTag : TagNames)
	{
		if (QuestTag.IsNone()) continue;

		auto Add = [this, &TagsManager](FName TagName)
		{
			// Skip if our editor-side set already knows about it (already added this session).
			if (CompiledNativeTagNames.Contains(TagName)) return;

			// Skip the FNativeGameplayTag construction if the tag is already registered with the
			// manager — typically from the runtime module's startup RegisterCompiledQuestTags pass,
			// which registers every compiled tag via AR metadata at editor launch. We still mark
			// CompiledNativeTagNames so subsequent batches' Contains check fast-paths through.
			//
			// Construction is ~3ms per tag (manager bookkeeping + tree-update side effects); for the
			// ~3000 native tags a typical project registers, skipping already-known ones saves the
			// bulk of Compile All Questlines time. Fresh tags (new content authored since last
			// editor session) still pay full construction cost — that's the actual structural floor.
			if (TagsManager.RequestGameplayTag(TagName, false).IsValid())
			{
				CompiledNativeTagNames.Add(TagName);
				return;
			}

			CompiledNativeTagNames.Add(TagName);
			CompiledNativeTags.Add(MakeUnique<FNativeGameplayTag>(FName("SimpleQuest"), FName("SimpleQuest"),
				TagName, TEXT(""), ENativeGameplayTagToken::PRIVATE_USE_MACRO_INSTEAD));
			bBatchAddedNewTag = true;   // a genuinely-new tag entered the tree -> a tree rebuild is warranted this batch
		};
		Add(QuestTag);

		if (FQuestTagComposer::IsIdentityTag(QuestTag))
		{
			for (EQuestStateLeaf Leaf : FQuestTagComposer::AllStateLeaves)
			{
				Add(FQuestTagComposer::MakeStateFact(QuestTag, Leaf));
			}
		}
	}
}

// Surgically unregister native tags a removed/recompiled graph no longer owns — but ONLY those no OTHER still-registered
// graph claims (shared tags like SimpleQuest.Outcome.Reached are registered by many graphs; unregistering one on a single
// removal would silently break every other graph resolving against it). Destroys just the orphaned FNativeGameplayTags +
// one tree refresh — O(removed) not the full O(all-tags) RebuildNativeTags(true) teardown. CALLER CONTRACT: CompiledTag-
// Registry must ALREADY reflect the post-change state (removed graph gone / recompiled graph's new tags in), so the
// "still claimed by another" check sees the correct remaining set.
void FSimpleQuestEditor::RemoveNativeTagsForGraph(const TArray<FName>& RemovedTagNames)
{
	if (RemovedTagNames.IsEmpty()) return;

	// Set of names STILL claimed by any remaining registered graph (incl. each identity tag's state-fact leaves, mirroring
	// AddNativeTagsForGraph's expansion — a still-used identity tag keeps its derived state facts alive).
	TSet<FName> StillClaimed;
	for (const TPair<FString, TArray<FName>>& Pair : CompiledTagRegistry)
	{
		for (const FName& Tag : Pair.Value)
		{
			StillClaimed.Add(Tag);
			if (FQuestTagComposer::IsIdentityTag(Tag))
			{
				for (EQuestStateLeaf Leaf : FQuestTagComposer::AllStateLeaves)
				{
					StillClaimed.Add(FQuestTagComposer::MakeStateFact(Tag, Leaf));
				}
			}
		}
	}

	// Orphans = everything the removed set owned (incl. state-fact leaves) that no remaining graph still claims.
	TSet<FName> Orphaned;
	auto ConsiderOrphan = [&](FName Tag)
	{
		if (!Tag.IsNone() && !StillClaimed.Contains(Tag)) Orphaned.Add(Tag);
	};
	for (const FName& Tag : RemovedTagNames)
	{
		ConsiderOrphan(Tag);
		if (FQuestTagComposer::IsIdentityTag(Tag))
		{
			for (EQuestStateLeaf Leaf : FQuestTagComposer::AllStateLeaves)
			{
				ConsiderOrphan(FQuestTagComposer::MakeStateFact(Tag, Leaf));
			}
		}
	}

	if (Orphaned.IsEmpty()) return;   // all still claimed elsewhere — tree unchanged, nothing to do.

	// Destroy just the orphaned natives (destructor unregisters from the manager) + drop from the lockstep name set.
	CompiledNativeTags.RemoveAll([&](const TUniquePtr<FNativeGameplayTag>& Native)
	{
		return Native.IsValid() && Orphaned.Contains(Native->GetTag().GetTagName());
	});
	for (const FName& Orphan : Orphaned)
	{
		CompiledNativeTagNames.Remove(Orphan);
	}

	UGameplayTagsManager::Get().EditorRefreshGameplayTagTree();

	UE_LOG(LogSimpleQuestCompiler, Display, TEXT("FSimpleQuestEditor::RemoveNativeTagsForGraph — unregistered %d orphaned tag(s), %d native(s) remain (tree refreshed)"),
		Orphaned.Num(), CompiledNativeTags.Num());
}

void FSimpleQuestEditor::HandlePickerCategoriesChanged()
{
	if (!GEditor) return;
	UAssetEditorSubsystem* AssetEditorSubsystem = GEditor->GetEditorSubsystem<UAssetEditorSubsystem>();
	if (!AssetEditorSubsystem) return;

	int32 ReconstructedCount = 0;
	for (UObject* Asset : AssetEditorSubsystem->GetAllEditedAssets())
	{
		UBlueprint* BP = Cast<UBlueprint>(Asset);
		if (!BP) continue;

		TArray<UEdGraph*> AllGraphs;
		BP->GetAllGraphs(AllGraphs);
		for (UEdGraph* Graph : AllGraphs)
		{
			if (!Graph) continue;
			for (UEdGraphNode* Node : Graph->Nodes)
			{
				// Only reconstruct nodes whose picker filter we actually source from settings.
				if (Cast<UK2Node_CompleteObjectiveWithOutcome>(Node) || Cast<UK2Node_ObserveQuestLifecycle>(Node))
				{
					Node->ReconstructNode();
					++ReconstructedCount;
				}
			}
		}
	}

	if (ReconstructedCount > 0)
	{
		UE_LOG(LogSimpleQuest, Verbose,
			TEXT("FSimpleQuestEditor::HandlePickerCategoriesChanged — refreshed %d K2 node(s) across open Blueprint editors."),
			ReconstructedCount);
	}
}

