// Copyright 2026, Greg Bussell, All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "PrerequisiteExpression.h"
#include "QuestNodeBase.generated.h"

class UQuestReward;

USTRUCT(BlueprintType)
struct FQuestOutcomeNodeList
{
    GENERATED_BODY()

    UPROPERTY(VisibleDefaultsOnly)
    TArray<FName> NodeTags;
};

UCLASS(Abstract, Blueprintable)
class SIMPLEQUEST_API UQuestNodeBase : public UObject
{
    GENERATED_BODY()

    friend class FQuestlineGraphCompiler;

public:
    DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnNodeActivated, UQuestNodeBase*, Node, FGameplayTag, InContextualTag);
    DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnNodeCompleted, UQuestNodeBase*, Node, FGameplayTag, OutcomeTag);

    FOnNodeActivated OnNodeActivated;
    FOnNodeCompleted OnNodeCompleted;

    /**
     * Activate this node with the given contextual tag. Sets ContextualTag and fires OnNodeActivated. Override in subclasses
     * to add activation behavior.
     */
    virtual void Activate(FGameplayTag InContextualTag);
    
    /** Resolve a raw, editor-time FName tag created by the graph compiler into the registered runtime FGameplayTag */
    void ResolveQuestTag(FName TagName);

protected:
    /**
     * Stable save key. Derived from the authoring node's GUID at compile time. Never hand-edited. Forms part of the GUID
     * chain for save data keying in linked graphs.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    FGuid QuestContentGuid;

    /**
     * Standalone routing tag for this node. Generated by the compiler from the questline asset name and node label. Used
     * for all event bus routing.
     * 
     * Format: Quest.<QuestlineName>.<SanitizedNodeLabel>
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    FGameplayTag QuestTag;

    /**
     * Call-site routing tag assigned by the subsystem at activation time. Equals QuestTag for root-level and standalone
     * nodes. Differs for nodes inside a shared linked graph where the parent provides a unique prefix.
     */
    UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly)
    FGameplayTag ContextualTag;

    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TMap<FGameplayTag, FQuestOutcomeNodeList> NextNodesByOutcome;

    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TSet<FName> NextNodesOnAnyOutcome;   // always activated regardless of outcome

    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TSet<FName> NextNodesOnAbandon;      // activated only by AbandonQuest()

    /**
     * A struct that holds the composable prerequisites for this quest graph node: the relevant tags representing events and their
     * required completion statuses along with the boolean-style logic by which they are combined.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    FPrerequisiteExpression PrerequisiteExpression;

    /** Reward granted on completion of this node. */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
    TSoftClassPtr<UQuestReward> Reward;

    /**
     * Whether completing this node should also complete the parent graph. Replaces bCompletesQuestline; works at any
     * graph depth.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    bool bCompletesParentGraph = false;

    /**
     * Whether activation of this node waits for a registered quest giver rather than starting immediately. Compiler-written
     * based on the presence of a giver-gate in the graph.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    bool bGiverGated = false;
    
    UPROPERTY()
    TWeakObjectPtr<UGameInstance> CachedGameInstance;
    
   public:

public:
    FORCEINLINE FGuid GetQuestGuid() const { return QuestContentGuid; }
    FORCEINLINE FGameplayTag GetQuestTag() const { return QuestTag; }
    FORCEINLINE FGameplayTag GetContextualTag() const { return ContextualTag; }
    FORCEINLINE void SetContextualTag(const FGameplayTag InTag) { ContextualTag = InTag; }
    FORCEINLINE const TArray<FName>* GetNextNodesForOutcome(FGameplayTag OutcomeTag) const;
    FORCEINLINE const TSet<FName>& GetNextNodesOnAnyOutcome() const { return NextNodesOnAnyOutcome; }
    FORCEINLINE const TSet<FName>& GetNextNodesOnAbandon() const { return NextNodesOnAbandon; }
    FORCEINLINE bool DoesCompleteParentGraph() const { return bCompletesParentGraph; }
    FORCEINLINE bool IsGiverGated() const { return bGiverGated; }
    void RegisterWithGameInstance(UGameInstance* InGameInstance) { CachedGameInstance = InGameInstance; }
    
};
