// Copyright 2026, Greg Bussell, All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "PrerequisiteExpression.h"
#include "Quests/Types/QuestNodeInfo.h"
#include "Quests/Types/QuestObjectiveActivationParams.h"
#include "QuestNodeBase.generated.h"

class UQuestReward;
struct FWorldStateFactAddedEvent;

/**
 * A single source-filtered entry destination. DestTag is the tag of a step or sub-node to activate when the parent quest
 * enters via a matching outcome from a matching source. SourceFilter is the compiled QuestTag (as FName) of the specific
 * source node required to fire this entry; a mismatch skips the entry. No "any source" sentinel, every compiled entry
 * must carry a concrete SourceFilter.
 */
USTRUCT(BlueprintType)
struct FQuestEntryDestination
{
    GENERATED_BODY()

    UPROPERTY(VisibleDefaultsOnly)
    FName DestTag;

    UPROPERTY(VisibleDefaultsOnly)
    FName SourceFilter;
};

/**
 * Value type for Quest's EntryStepTagsByOutcome map. Wraps a per-outcome list of source-filtered destinations: one
 * entry per Entry-node output pin that fires for this outcome, each tagged with the parent source required to fire it.
 */
USTRUCT(BlueprintType)
struct FQuestEntryRouteList
{
    GENERATED_BODY()

    UPROPERTY(VisibleDefaultsOnly)
    TArray<FQuestEntryDestination> Destinations;
};

USTRUCT(BlueprintType)
struct FQuestOutcomeNodeList
{
    GENERATED_BODY()

    UPROPERTY(VisibleDefaultsOnly)
    TArray<FName> NodeTags;
};

UCLASS(Abstract, Blueprintable)
class SIMPLEQUEST_API UQuestNodeBase : public UObject
{
    GENERATED_BODY()

    friend class FQuestlineGraphCompiler;
    friend class UQuestManagerSubsystem;

public:
    DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnNodeActivated, UQuestNodeBase*, Node, FGameplayTag, InContextualTag);
    DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnNodeCompleted, UQuestNodeBase*, Node, FGameplayTag, OutcomeTag);
    DECLARE_DYNAMIC_DELEGATE_OneParam (FOnNodeForwardActivated, UQuestNodeBase*, Node);

    FOnNodeActivated OnNodeActivated;
    FOnNodeCompleted OnNodeCompleted;
    
    /**
     * Fired by utility nodes (SetBlocked, ClearBlocked, GroupSignalSetter, GroupSignalGetter) instead of OnNodeActivated/OnNodeCompleted.
     * Manager chains NextNodesOnForward without writing any lifecycle facts.
     */
    FOnNodeForwardActivated OnNodeForwardActivated;

    /**
     * Entry point for node activation. Base implementation evaluates PrerequisiteExpression against WorldState; activates immediately
     * if satisfied, otherwise defers. UQuestStep overrides this to bypass prerequisite gating for non-giver steps (prerequisites gate
     * progression or completion instead — see EPrerequisiteGateMode).
     */
    virtual void Activate(FGameplayTag InContextualTag);
    
    /** Resolve a raw, editor-time FName tag created by the graph compiler into the registered runtime FGameplayTag */
    void ResolveQuestTag(FName TagName);
    
protected:
    /**
     * Called when prerequisites are confirmed satisfied. Sets ContextualTag and fires OnNodeActivated. Override in subclasses
     * for additional activation behavior; always call Super::ActivateInternal first.
     */
    virtual void ActivateInternal(FGameplayTag InContextualTag);
    
    /**
     * Called by the manager when this node is deactivated while Active. Override in subclasses to destroy live objectives
     * and cancel any subscriptions specific to the active lifecycle. Default implementation cancels deferred prereq subscriptions.
     * Always call Super::DeactivateInternal.
     */
    virtual void DeactivateInternal(FGameplayTag InContextualTag);
    
    /**
     * Called by utility nodes instead of the normal activation/completion lifecycle. Default implementation fires OnNodeForwardActivated
     * so the manager can chain NextNodesOnForward. Utility nodes call this after completing their utility action.
     */
    virtual void ForwardActivation();

    /**
     * Clears every member set during an earlier Activate / Deactivate cycle. Called by
     * UQuestManagerSubsystem::ActivateQuestlineGraph before each PIE session wires the node back into a live subsystem —
     * the compiled instances persist across PIE sessions (they live on the UQuestlineGraph asset), so any delegate
     * handles or scratch state from a prior session are stale and must be dropped. Override on subclasses that add
     * their own transient members; always call Super first.
     */
    virtual void ResetTransientState();
    
    /**
     * Stable save key. Derived from the authoring node's GUID at compile time. Never hand-edited. Forms part of the GUID
     * chain for save data keying in linked graphs.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    FGuid QuestContentGuid;

    /**
     * Standalone routing tag for this node. Generated by the compiler from the questline asset name and node label. Used
     * for all event bus routing.
     * 
     * Format: Quest.<QuestlineName>.<SanitizedNodeLabel>
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    FGameplayTag QuestTag;

    /**
     * Call-site routing tag assigned by the subsystem at activation time. Equals QuestTag for root-level and standalone
     * nodes. Differs for nodes inside a shared linked graph where the parent provides a unique prefix.
     */
    UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly)
    FGameplayTag ContextualTag;
    
    /**
     * Transient scratch slot for activation-time params stamped by the manager before Activate runs. Populated by
     * ChainToNextNodes (cascade pre-stamp), HandleGiveQuestEvent, HandleActivationRequest, and ActivateNodeByTag's
     * Quest-boundary forwarder. Consumed and cleared by the concrete subclass during its activation (UQuestStep merges
     * additively with authored defaults; UQuest forwards to inner entries). Not serialized — save/load restoration
     * republishes the activation event rather than persisting this stash.
     */
    UPROPERTY(Transient)
    FQuestObjectiveActivationParams PendingActivationParams;

    /**
     * Map of tags representing each discrete outcome possible as set on either the UQuestObjective or by the exit nodes on the
     * child graph contained by this node.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TMap<FGameplayTag, FQuestOutcomeNodeList> NextNodesByOutcome;

    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TSet<FName> NextNodesOnAnyOutcome;   // always activated regardless of outcome

    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TSet<FName> NextNodesOnAbandon;       // DEPRECATED — remove after compiler migration
    
    /** Nodes to activate normally when this node deactivates (Deactivated output → Activate input). */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TSet<FName> NextNodesOnDeactivation;

    /** Nodes to deactivate when this node deactivates (Deactivated output to any Deactivate inputs). */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TSet<FName> NextNodesToDeactivateOnDeactivation;

    /** Nodes to activate as a pass-through (utility node chaining; no lifecycle writes). */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TSet<FName> NextNodesOnForward;
    
    /**
     * A struct that holds the composable prerequisites for this quest graph node: the relevant tags representing events and their
     * required completion statuses along with the boolean-style logic by which they are combined.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    FPrerequisiteExpression PrerequisiteExpression;

    /** Reward granted on completion of this node. */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
    TSoftClassPtr<UQuestReward> Reward;

    /**
     * Whether completing this node should also complete the parent graph. Replaces bCompletesQuestline; works at any
     * graph depth.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    bool bCompletesParentGraph = false;
    
    UPROPERTY()
    TWeakObjectPtr<UGameInstance> CachedGameInstance;
    
    void DeferActivation(FGameplayTag InContextualTag);

    /**
     * Compiled display metadata. DisplayName baked by the compiler from the unsanitized editor node title; QuestTag resolved at
     * runtime alongside the standalone QuestTag field. Read by the manager when assembling outbound FQuestEventContext.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    FQuestNodeInfo NodeInfo;

private:
    // Stores the contextual tag while waiting for prerequisites to clear
    FGameplayTag DeferredContextualTag;

    // Per-leaf-tag subscription handles; cleared when prerequisites are satisfied
    TMap<FGameplayTag, FDelegateHandle> PrereqSubscriptionHandles;

    void OnPrereqFactAdded(FGameplayTag Channel, const FWorldStateFactAddedEvent& Event);
    void TryActivateDeferred();

    /**
     * Set by the manager when this node enters PendingGiver state. When true, prerequisites gate actual activation (giver semantics).
     * When false, prerequisites gate progression only — activation is immediate.
     */
    bool bWasGiverGated = false;
    
public:
    FORCEINLINE FGuid GetQuestGuid() const { return QuestContentGuid; }
    FORCEINLINE FGameplayTag GetQuestTag() const { return QuestTag; }
    FORCEINLINE FGameplayTag GetContextualTag() const { return ContextualTag; }
    FORCEINLINE void SetContextualTag(const FGameplayTag InTag) { ContextualTag = InTag; }
    const TArray<FName>* GetNextNodesForOutcome(FGameplayTag OutcomeTag) const;
    FORCEINLINE const TSet<FName>& GetNextNodesOnAnyOutcome() const { return NextNodesOnAnyOutcome; }
    FORCEINLINE const TSet<FName>& GetNextNodesOnAbandon() const { return NextNodesOnAbandon; }
    FORCEINLINE const TSet<FName>& GetNextNodesOnDeactivation() const { return NextNodesOnDeactivation; }
    FORCEINLINE const TSet<FName>& GetNextNodesToDeactivateOnDeactivation() const { return NextNodesToDeactivateOnDeactivation; }
    FORCEINLINE const TSet<FName>& GetNextNodesOnForward() const { return NextNodesOnForward; }
    FORCEINLINE bool DoesCompleteParentGraph() const { return bCompletesParentGraph; }
    FORCEINLINE bool IsGiverGated() const { return bWasGiverGated; }
    void RegisterWithGameInstance(UGameInstance* InGameInstance) { CachedGameInstance = InGameInstance; }
    FORCEINLINE const FQuestNodeInfo& GetNodeInfo() const { return NodeInfo; }

    
};
