;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QuickStart.Chapter_3.Step_A",NewTagName="SimpleQuest.Questline.QuickStart.Chapter_3.Either_Giver")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QuickStart.Chapter_3.Step_B",NewTagName="SimpleQuest.Questline.QuickStart.Chapter_3.Reuse_Giver")
+GameplayTagList=(Tag="MyGameTags.Fork.LeftPath",DevComment="")
+GameplayTagList=(Tag="MyGameTags.Fork.RightPath",DevComment="")
+GameplayTagList=(Tag="MyGameTags.Refusal.WrongTag",DevComment="")
+GameplayTagList=(Tag="MyGameTags.Testing.TestChild",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.ActivationGroup.Group1.ChildA",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.ActivationGroup.MasterUnlock",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Fact.QuickStart.Blocking.DoorOpen",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Fact.QuickStart.ChaptersUnlocked",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Fact.QuickStart.TutorialStarted",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Outcome.Defeat",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Outcome.Fork.A",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Outcome.Fork.B",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Outcome.GameOver",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Outcome.Left",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Outcome.MasterUnlock",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Outcome.Right",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Reward.Currency.Gold",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.Reward.Currency.Runes",DevComment="")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QuickStart.Chapter_8.First.Step",NewTagName="SimpleQuest.Questline.QuickStart.Chapter_8.West_Patrol.Waypoint_1")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QuickStart.Chapter_8.First.Step_1",NewTagName="SimpleQuest.Questline.QuickStart.Chapter_8.West_Patrol.Waypoint_2")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QuickStart.Chapter_8.First",NewTagName="SimpleQuest.Questline.QuickStart.Chapter_8.West_Patrol")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QuickStart.Chapter_8.Second.Step",NewTagName="SimpleQuest.Questline.QuickStart.Chapter_8.East_Patrol.Waypoint_1")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QuickStart.Chapter_8.Second.Step_1",NewTagName="SimpleQuest.Questline.QuickStart.Chapter_8.East_Patrol.Waypoint_2")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QuickStart.Chapter_8.Second",NewTagName="SimpleQuest.Questline.QuickStart.Chapter_8.East_Patrol")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.First.Step",NewTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.West_Patrol.Waypoint_1")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.First.Step_1",NewTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.West_Patrol.Waypoint_2")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.First",NewTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.West_Patrol")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.Second.Step",NewTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.East_Patrol.Waypoint_1")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.Second.Step_1",NewTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.East_Patrol.Waypoint_2")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.Second",NewTagName="SimpleQuest.Questline.QL_Ch8_LinkedQuestlines.East_Patrol")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QL_SubTest.Step",NewTagName="SimpleQuest.Questline.QL_PatrolRoute.Waypoint_1")
+GameplayTagRedirects=(OldTagName="SimpleQuest.Questline.QL_SubTest.Step_1",NewTagName="SimpleQuest.Questline.QL_PatrolRoute.Waypoint_2")
