;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="QuestPrereqGroup",NewTagName="QuestPrereqRule")
+GameplayTagRedirects=(OldTagName="QuestPrereqGroup.GroupA",NewTagName="QuestPrereqRule.GroupA")
+GameplayTagList=(Tag="Quest.Outcome.LostPartner.Quit",DevComment="")
+GameplayTagList=(Tag="Quest.Outcome.Solved",DevComment="")
+GameplayTagList=(Tag="Quest.Outcome.Triumph",DevComment="")
+GameplayTagList=(Tag="Quest.Outcome.Victory",DevComment="")
+GameplayTagList=(Tag="QuestActivationGroup.Group1",DevComment="")
+GameplayTagList=(Tag="QuestActivationGroup.Group2",DevComment="")
+GameplayTagList=(Tag="QuestPrereqRule.GroupA",DevComment="")
+GameplayTagList=(Tag="QuestPrereqRule.GroupB",DevComment="")
+GameplayTagList=(Tag="QuestPrereqRule.GroupC",DevComment="")

