;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="QuestPrereqGroup",NewTagName="SimpleQuest.QuestPrereqRule")
+GameplayTagRedirects=(OldTagName="QuestPrereqGroup.GroupA",NewTagName="SimpleQuest.QuestPrereqRule.GroupA")
+GameplayTagRedirects=(OldTagName="Quest",NewTagName="SimpleQuest.Quest")
+GameplayTagRedirects=(OldTagName="Quest.Outcome",NewTagName="SimpleQuest.QuestOutcome")
+GameplayTagRedirects=(OldTagName="QuestState",NewTagName="SimpleQuest.QuestState")
+GameplayTagRedirects=(OldTagName="QuestPrereqRule",NewTagName="SimpleQuest.QuestPrereqRule")
+GameplayTagRedirects=(OldTagName="QuestActivationGroup",NewTagName="SimpleQuest.QuestActivationGroup")
+GameplayTagRedirects=(OldTagName="Quest.Outcome.LostPartner.Quit",NewTagName="SimpleQuest.QuestOutcome.LostPartner.Quit")
+GameplayTagRedirects=(OldTagName="Quest.Outcome.Solved",NewTagName="SimpleQuest.QuestOutcome.Solved")
+GameplayTagRedirects=(OldTagName="Quest.Outcome.Triumph",NewTagName="SimpleQuest.QuestOutcome.Triumph")
+GameplayTagRedirects=(OldTagName="Quest.Outcome.Victory",NewTagName="SimpleQuest.QuestOutcome.Victory")
+GameplayTagRedirects=(OldTagName="QuestActivationGroup.Group1",NewTagName="SimpleQuest.QuestActivationGroup.Group1")
+GameplayTagRedirects=(OldTagName="QuestActivationGroup.Group2",NewTagName="SimpleQuest.QuestActivationGroup.Group2")
+GameplayTagRedirects=(OldTagName="QuestPrereqRule.GroupB",NewTagName="SimpleQuest.QuestPrereqRule.GroupB")
+GameplayTagRedirects=(OldTagName="QuestPrereqRule.GroupC",NewTagName="SimpleQuest.QuestPrereqRule.GroupC")
+GameplayTagRedirects=(OldTagName="QuestPrereqRule.TestGroup",NewTagName="SimpleQuest.QuestPrereqRule.TestGroup")
+GameplayTagRedirects=(OldTagName="Quest.Channel",NewTagName="SimpleQuest.QuestChannel")
+GameplayTagRedirects=(OldTagName="Quest.Channel.ActivationRequest",NewTagName="SimpleQuest.QuestChannel.ActivationRequest")
+GameplayTagRedirects=(OldTagName="Quest.Channel.QuestTarget",NewTagName="SimpleQuest.QuestChannel.QuestTarget")
+GameplayTagRedirects=(OldTagName="Quest.Channel.GiverRegistered",NewTagName="SimpleQuest.QuestChannel.GiverRegistered")
+GameplayTagRedirects=(OldTagName="Quest.Channel.Given",NewTagName="SimpleQuest.QuestChannel.Given")
+GameplayTagRedirects=(OldTagName="Quest.Channel.Deactivate",NewTagName="SimpleQuest.QuestChannel.Deactivate")
+GameplayTagRedirects=(OldTagName="Quest.Channel.Abandoned",NewTagName="SimpleQuest.QuestChannel.Abandoned")
+GameplayTagRedirects=(OldTagName="Quest.Outcome.Reached",NewTagName="SimpleQuest.QuestOutcome.Reached")
+GameplayTagRedirects=(OldTagName="Quest.Outcome.TargetKilled",NewTagName="SimpleQuest.QuestOutcome.TargetKilled")
+GameplayTagRedirects=(OldTagName="Quest.Outcome.LostPartner",NewTagName="SimpleQuest.QuestOutcome.LostPartner")
+GameplayTagRedirects=(OldTagName="Quest.Outcome.LostPartner.Died",NewTagName="SimpleQuest.QuestOutcome.LostPartner.Died")
+GameplayTagList=(Tag="SimpleQuest.QuestActivationGroup.Group1",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestActivationGroup.Group2",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestActivationGroup.Group3",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestOutcome.LostPartner.Quit",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestOutcome.Solved",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestOutcome.Triumph",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestOutcome.Victory",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestPrereqRule.GroupA",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestPrereqRule.GroupB",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestPrereqRule.GroupC",DevComment="")
+GameplayTagList=(Tag="SimpleQuest.QuestPrereqRule.TestGroup",DevComment="")

