"""Project-relative paths for the resolver verification scripts.

These scripts read the editor's log and write fixture folders under the project's Saved/ directory, both of which sit at
a fixed offset from this file (Scripts/ResolverVerification/ -> project root). Deriving them here rather than hardcoding
an absolute path in each script keeps the harness runnable from any clone.

Saved/ is gitignored, so nothing this module points at is version-controlled: the fixtures are REGENERATED by the
make_*.py scripts from an export of the probe asset, and the log is whatever the last editor session produced.
"""
import os

PROJECT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

EXPORT_ROOT = os.path.join(PROJECT, "Saved", "QuestExport")
LOG = os.path.join(PROJECT, "Saved", "Logs", "SimpleQuestDemo.log")
